CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE auth_challenges (
    id VARCHAR(36) PRIMARY KEY,
    admin_user_id BIGINT NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_auth_challenges_admin_users
        FOREIGN KEY (admin_user_id) REFERENCES admin_users (id)
);

CREATE TABLE floors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(255),
    sort_order INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE seat_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    color_hex VARCHAR(16) NOT NULL,
    has_monitors BOOLEAN NOT NULL DEFAULT FALSE,
    standing BOOLEAN NOT NULL DEFAULT FALSE,
    requires_chair BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id BIGINT NOT NULL,
    seat_type_id BIGINT NOT NULL,
    row_index INT NOT NULL,
    column_index INT NOT NULL,
    label VARCHAR(80) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_seats_floors
        FOREIGN KEY (floor_id) REFERENCES floors (id),
    CONSTRAINT fk_seats_seat_types
        FOREIGN KEY (seat_type_id) REFERENCES seat_types (id)
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_id BIGINT NOT NULL,
    booking_date DATE NOT NULL,
    booked_by_name VARCHAR(160) NOT NULL,
    booked_by_normalized_name VARCHAR(160) NOT NULL,
    booked_by_email VARCHAR(200),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_bookings_seats
        FOREIGN KEY (seat_id) REFERENCES seats (id),
    CONSTRAINT uk_bookings_seat_date UNIQUE (seat_id, booking_date)
);

CREATE TABLE booking_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id BIGINT NOT NULL,
    seat_id BIGINT NULL,
    booking_id BIGINT NULL,
    seat_label VARCHAR(80) NOT NULL,
    booking_date DATE NOT NULL,
    actor_name VARCHAR(160) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_booking_audit_events_floors
        FOREIGN KEY (floor_id) REFERENCES floors (id),
    CONSTRAINT fk_booking_audit_events_seats
        FOREIGN KEY (seat_id) REFERENCES seats (id)
);

CREATE INDEX idx_seats_floor_effective
    ON seats (floor_id, effective_from, effective_to);

CREATE INDEX idx_bookings_date
    ON bookings (booking_date);

CREATE INDEX idx_bookings_name_date
    ON bookings (booked_by_normalized_name, booking_date);

CREATE INDEX idx_booking_audit_events_date
    ON booking_audit_events (booking_date);
